---
# - name: "upgrade packages."
#   become: true
#   apt:
#     upgrade: "yes"
# - copy:
#       src: /home/ashraf/Documents/udacity-project/util/docker-compose.yml
#       dest: /home/ubuntu
      
- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

# - copy:
#     remote_dest: yes
#     src: /home/ashraf/Documents/udacity-project/util/docker-compose.yml
#     dest: /home/ubuntu

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Install docker packages
  remote_user: ubuntu
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
  tags:
    - docker
- name: Add Docker s official GPG key
  remote_user: ubuntu
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - docker
- name: Verify that we have the key with the fingerprint
  remote_user: ubuntu
  apt_key:
    id: 0EBFCD88
    state: present
  tags:
    - docker
# - name: Set up the stable repository
#   remote_user: ubuntu
#   apt_repository:
#     repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
#     state: present
#     update_cache: yes
#   tags:
#     - docker
- name: Update apt packages
  remote_user: ubuntu
  apt:
    update_cache: yes
  tags:
    - docker
- name: Install docker
  remote_user: ubuntu
  apt: 
    name: docker
    state: latest
    update_cache: yes
  tags:
    - docker
# - name: Add remote "ubuntu" user to "docker" group
#   remote_user: ubuntu
#   user:
#     name: "ubuntu"
#     group: "docker"
#     append: yes
#   tags:
#     - docker
- name: Install docker-compose
  remote_user: ubuntu
  get_url: 
    url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x,o+x'
- name: Ibs
  command:
      curl -L "https://github.com/docker/compose/releases/download/v2.1.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      chmod +x /usr/local/bin/docker-compose
      ln -sf /usr/local/bin/docker-compose  /usr/bin
      sudo systemctl start docker

# - copy:
#     src: /home/ashraf/Documents/udacity-cloud-devops-final-project/util/docker-compose.yml
#     dest: /home/ubuntu/
# - name: Copy file with owner and permissions
#   copy:
#     become: True
#     src: '/home/ashraf/Documents/udacity-project/util/docker-compose.yml'
#     dest: /home/ubuntu/
#     owner: root
#     group: root
#     mode: '777'
- name: copy Docker file with playbook 
  become: true
  template: src=docker-compose.yml dest=/home/ubuntu/
  # copy: 
  #   src: /home/ashraf/Documents/udacity-project/util/docker-compose.yml
  #   dest: /var/www/html
  #   owner: root
  #   group: root        
  #   mode: 777
- name: Run PostgresQL DB
  become: True
  shell:
    cmd: "docker-compose -f docker-compose.yml up -d"
    chdir: .

    